In [1]:
import pandas as pd

In [43]:
df=pd.read_csv("../data/raw/duplicates_scenario.csv")
print("Successfully read the csv file")

Successfully read the csv file

In [44]:
df.head()

   ID  Name  GPA         Email
0   1  John  3.5  ad@gmail.com
1   2  Sara  3.9  df@gmail.com
2   2  Sara  3.9  ad@gmail.com
3   1  John  3.5  ad@gmail.com

In [41]:
df.shape

(4, 4)

In [45]:
df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [46]:
df[df.duplicated()]

   ID  Name  GPA         Email
3   1  John  3.5  ad@gmail.com

In [49]:
df.duplicated(subset=["Email"])

df.drop_duplicates(subset=["Email"])

   ID  Name  GPA         Email
0   1  John  3.5  ad@gmail.com
1   2  Sara  3.9  df@gmail.com

In [38]:
df.drop_duplicates(keep="last",inplace=True)
#df[df.duplicated()]

df

   ID  Name  GPA
0   1  John  3.5
1   2  Sara  3.9